### ISSUE TITLE
Is this repository still maintained

### ISSUE THREAD

**Issue by dutch-game-studio** [Brixto/flame_texturepacker#1]
Currently null safety is not supported, will this be added? Is this package still maintained?

**Comment by spydon** [comment]
@Brixto if you are not interested in maintaining this library, could you maybe transfer it to flame-engine.org on pub.dev and we can update it to Flame 1.0.0 and continue the maintenance? :)

**Comment by Brixto** [comment]
Will update or transfer it asap. Give me some hours to look into it.

**Comment by spydon** [comment]
@Brixto you could follow the `extension` convention that we have for other things that can be loaded, then it would look something like this (haven't tried it):
https://stackoverflow.com/questions/70666490/how-to-align-sprites-sequentially-in-a-line-and-extract-them-as-a-png-format-wit/70671052#70671052

**Comment by Brixto** [comment]
Updated the library to version 2.0.0+2 including null-safety migration and update to flame-engine v1.
Also converted to extenstion convetion. 
https://pub.dev/packages/flame_texturepacker

**Comment by spydon** [comment]
Looks great! A small update of the `README.md` would be good too.
