### ISSUE TITLE
Bug in fromJSONAtlas

### ISSUE THREAD

**Issue by Yaroslav-Zagumennikov** [Brixto/flame_texturepacker#5]
![image](https://user-images.githubusercontent.com/91648112/205097604-7f0e1137-6fb0-44df-869f-3fcc61961994.png)
![image](https://user-images.githubusercontent.com/91648112/205097627-f9974388-6327-4077-aed6-10d1ace56d29.png)
What is problem. I install all library

**Comment by Yaroslav-Zagumennikov** [comment]
![image](https://user-images.githubusercontent.com/91648112/205099225-0826ca2f-2270-4867-8f70-d6edde6be50f.png)

**Comment by Brixto** [comment]
Does your class extend the FlameGame or Game class?
TexturepackerLoader is a extension coupled with the Game class

**Comment by Brixto** [comment]
![image](https://user-images.githubusercontent.com/5895358/205100849-2bd2ae35-916c-43bf-877c-05008dc80da4.png)

**Comment by Yaroslav-Zagumennikov** [comment]
sorry bro, i did it in a class that extends SpriteComponent
![image](https://user-images.githubusercontent.com/91648112/205101794-44cd3e58-cdcb-428e-9e44-169aca62b60c.png)
in FlameGame he work
